# jobeet_job_backend_category:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                JobeetJob
#     module:               backend_category
#     prefix_path:          /backend_category
#     column:               id
#     with_wildcard_routes: true

# jobeet_affiliate_backend_job:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                JobeetJob
#     module:               backend_job
#     prefix_path:          /backend_job
#     column:               id
#     with_wildcard_routes: true

# jobeet_affiliate_backend_category:
#   class: sfDoctrineRouteCollection
#   options:
#     model:                JobeetAffiliate
#     module:               backend_category
#     prefix_path:          /backend_category
#     column:               id
#     with_wildcard_routes: true

jobeet_affiliate:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetAffiliate
    module:               backend_affiliate
    prefix_path:          /backend/affiliate
    column:               id
    with_wildcard_routes: true

jobeet_category:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetCategory
    module:               backend_category
    prefix_path:          /backend/category
    column:               id
    with_wildcard_routes: true

jobeet_job:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetJob
    module:               backend_job
    prefix_path:          /backend/job
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url: /backend/login
  param: {module: sfGuardAuth, action: signin}

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /backend/users
    with_wildcard_routes: true
  param:
    skip_i18n: true
  

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: backend_job, action: index }

