<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/06/27 11:32:14
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
