<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/07/01 13:14:17
sfConfig::add(array(
  'mod_backend_category_enabled' => true,
  'mod_backend_category_view_class' => 'sfPHP',
));
