<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/07/01 13:14:38
sfConfig::add(array(
  'mod_sfjobeetcategory_enabled' => true,
  'mod_sfjobeetcategory_view_class' => 'sfPHP',
));
