<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/06/27 11:17:50
sfConfig::add(array(
  'mod_backend_category_enabled' => true,
  'mod_backend_category_view_class' => 'sfPHP',
));
