<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/06/27 11:17:39
sfConfig::add(array(
  'mod_backend_affiliate_enabled' => true,
  'mod_backend_affiliate_view_class' => 'sfPHP',
));
