generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true
    # actions_base_class:    sfActions

    config:
      actions: ~ #Configuración por defecto de las acciones se encuentran en la lista como en los formilarios
      fields:   #Configuración por defecto para los campos
        is_activated: {label: Activated?, help: Whether the user has activated the job, or not  }
        is_public: {label: Public?}
      
      list:
        title: Job Management
        layout:  stacked
        display: [company, position, location, url, is_activated, email] #se mantienen ya que se usa para filtrar
        params:  |
          %%is_activated%% <small>%%jobeet_category%%</small> -    %%company%%
            (<em>%%email%%</em>) is looking for a %%=position%% (%%location%%)
        max_per_page: 10
        sort: [expires_at, desc]
        batch_actions:
          _delete: ~
          extend: ~
        object_actions:
          extend: ~
          _edit: ~
          _delete: ~
        actions:
          deleteNeverActivated: {label: Delete Never Activate Jobs}
        table_method: retrieveBackendJobList
          
        # fields:   #Configuración por defecto para los campos <- esto es por si quiero label expecifico solo en lista y etc
        # is_activated: {label: Activated?, help: Whether the user has activated the job, or  not  }
          
      filter:   #Configuración de los filtros
        display: [category_id, company, position, description, is_activated, is_public, email, expires_at]
      
      form:     #Configuración del fomulario form/new/edit
        class: BackendJobeetJobForm #Seteamos la clase del formulario backend hija de la deel frontend
        display:
          Content: [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
          Admin: [_generated_token, is_activated, expires_at]
      edit:    
        title: Editing Job "%%company%%" is looking for a '%%position%%'
      new:     
        title: Job Creation
