<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/07/02 12:03:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=jobeet_test',
  'username' => 'postgres',
  'password' => '123',
  'name' => 'doctrine',
)),);
