<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/06/24 16:16:41
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 4,
  'app_max_jobs_on_category' => 10,
));
