<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/06/24 16:16:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=jobeet',
  'username' => 'postgres',
  'password' => '123',
  'name' => 'doctrine',
)),);
