<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/07/02 12:02:24
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
