<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/06/27 10:50:28
sfConfig::add(array(
  'mod_sfjobeetcategory_enabled' => true,
  'mod_sfjobeetcategory_view_class' => 'sfPHP',
));
