<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/07/02 12:03:26
sfConfig::add(array(
  'mod_sfjobeetaffiliate_enabled' => true,
  'mod_sfjobeetaffiliate_view_class' => 'sfPHP',
));
