<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/07/02 12:02:26
sfConfig::add(array(
  'mod_sfjobeetcategory_enabled' => true,
  'mod_sfjobeetcategory_view_class' => 'sfPHP',
));
